### PR TITLE
Update selectors for noInlineHighlight gatsby option

### PR DESCRIPTION
**Pull request by mdrx-io**
I didn't look too deep into how these selectors are used or why they were originally added, but without them [this gatsby plugin option](https://github.com/gatsbyjs/gatsby/pull/7554) doesn't work correctly.

### CODE REVIEW

**Comment by kyleshevlin** [comment]
Was looking to add this to my Gatsby blog and this PR is necessary for me. Without the `[class*='language-']` attribute on the CSS selectors, the styles aren't specific enough.

Here's a before picture of my current prism theme. I'd like to keep the light gray for inline code:

Screen Shot 2020-04-09 at 2 54 41 PM

And here's what happens adding this package because the css isn't specific enough:

Screen Shot 2020-04-09 at 2 54 52 PM

Hoping this gives the PR a bump, would be a great addition. Thanks for making the port @SaraVieira. 👋

**Comment by SaraVieira** [comment]
Hey!

Tomorrow is a holiday here so j have some time to set up this project again on my computer and will fix this :)

Also add the light version

**Comment by kyleshevlin** [comment]
That's awesome! Thanks @SaraVieira, enjoy the holiday weekend.

**Review by SaraVieira — APPROVED** [review]
Sorry it took me so long! Merged and thank you so much!

**Comment by SaraVieira** [comment]
👋

All published in `prism-theme-night-owl@1.4.0` including light and no italic themes 🎉

**Pull request merged**
